export const REPO_SEARCH_TEXT = {
  title: 'Find and Replace in Repository',
  findLabel: 'Find',
  findPlaceholder: 'Search text across all markdown files...',
  replaceLabel: 'Replace (optional)',
  replacePlaceholder: 'Replacement text...',
  caseSensitive: 'Case sensitive',
  useRegex: 'Use regex',
  searching: 'Searching...',
  searchButton: 'Search Repository',
  replaceAllButton: 'Replace All in Repo',
  replaceInFile: 'Replace in file',
  close: 'Close',
  searchFailed: 'Search failed',
  replaceFailed: 'Replace failed',
  emptyQueryError: 'Please enter a search query',
  replaceMissingError: 'Please enter both search and replace text',
  noMatches: 'No matches found',
  replaceAllTooltip: 'Replace all matches in all files',
  repoSearchHint: 'Searches only .md files in the repository',
  replaceAllConfirmSuffix: 'This action will modify files on disk.',
} as const;
