import enGbSettingsDialog from "../../i18n/en-GB/settingsDialog.json";

export const SETTINGS_KEYS = {
  title: "settingsDialog.title",
  close: "settingsDialog.close",
  copySnackbar: "settingsDialog.copySnackbar",
  tabAppSettings: "settingsDialog.tabs.appSettings",
  tabRepository: "settingsDialog.tabs.repository",
  tabProfiles: "settingsDialog.tabs.profiles",
  tabExport: "settingsDialog.tabs.export",
  tabLogs: "settingsDialog.tabs.logs",
  failedLoadConfig: "settingsDialog.error.failedLoadConfig",
  appSettingsSaved: "settingsDialog.success.appSettingsSaved",
  failedSaveAppSettings: "settingsDialog.error.failedSaveAppSettings",
  failedSetLanguage: "settingsDialog.error.failedSetLanguage",
  localRepoNoSync: "settingsDialog.success.localRepoNoSync",
  gitFieldsRequired: "settingsDialog.error.gitFieldsRequired",
  s3FieldsRequired: "settingsDialog.error.s3FieldsRequired",
  repoSettingsSaved: "settingsDialog.success.repoSettingsSaved",
  failedSaveRepoSettings: "settingsDialog.error.failedSaveRepoSettings",
  noOpenNote: "settingsDialog.error.noOpenNote",
  exportCancelledMessage: "settingsDialog.exportCancelledMessage",
  failedExportNote: "settingsDialog.error.failedExportNote",
  failedExportRepository: "settingsDialog.error.failedExportRepository",
  noteExportedPrefix: "settingsDialog.success.noteExportedPrefix",
  repositoryExportedPrefix: "settingsDialog.success.repositoryExportedPrefix",
  profileSwitched: "settingsDialog.success.profileSwitched",
  failedSwitchProfile: "settingsDialog.error.failedSwitchProfile",
  profileNameRequired: "settingsDialog.error.profileNameRequired",
  allGitFieldsRequired: "settingsDialog.error.allGitFieldsRequired",
  allS3FieldsRequired: "settingsDialog.error.allS3FieldsRequired",
  profileCreated: "settingsDialog.success.profileCreated",
  failedCreateProfile: "settingsDialog.error.failedCreateProfile",
  deleteProfileConfirm: "settingsDialog.confirm.deleteProfile",
  switchProfilePrefix: "settingsDialog.confirm.switchProfilePrefix",
  switchProfileSuffix: "settingsDialog.confirm.switchProfileSuffix",
  switchProfileFallbackName: "settingsDialog.confirm.switchProfileFallbackName",
  profileDeleted: "settingsDialog.success.profileDeleted",
  failedDeleteProfile: "settingsDialog.error.failedDeleteProfile",
  failedLoadLogsFolder: "settingsDialog.error.failedLoadLogsFolder",
  failedOpenRepositoryFolder: "settingsDialog.error.failedOpenRepositoryFolder",
  failedOpenLogsFolder: "settingsDialog.error.failedOpenLogsFolder",
  localRepoSecondaryLabel: "settingsDialog.localRepoSecondaryLabel",
} as const;

export const SETTINGS_TEXT = {
  title: enGbSettingsDialog.title,
  tabs: [
    enGbSettingsDialog.tabs.appSettings,
    enGbSettingsDialog.tabs.repository,
    enGbSettingsDialog.tabs.profiles,
    enGbSettingsDialog.tabs.export,
    enGbSettingsDialog.tabs.logs,
  ],
} as const;
