import enGbRepoSearchDialog from "../../i18n/en-GB/repoSearchDialog.json";

export const REPO_SEARCH_KEYS = {
  title: "repoSearchDialog.title",
  findLabel: "repoSearchDialog.findLabel",
  findPlaceholder: "repoSearchDialog.findPlaceholder",
  replaceLabel: "repoSearchDialog.replaceLabel",
  replacePlaceholder: "repoSearchDialog.replacePlaceholder",
  caseSensitive: "repoSearchDialog.caseSensitive",
  useRegex: "repoSearchDialog.useRegex",
  searching: "repoSearchDialog.searching",
  searchButton: "repoSearchDialog.searchButton",
  replaceAllButton: "repoSearchDialog.replaceAllButton",
  replaceInFile: "repoSearchDialog.replaceInFile",
  close: "repoSearchDialog.close",
  searchFailed: "repoSearchDialog.searchFailed",
  replaceFailed: "repoSearchDialog.replaceFailed",
  emptyQueryError: "repoSearchDialog.emptyQueryError",
  replaceMissingError: "repoSearchDialog.replaceMissingError",
  noMatches: "repoSearchDialog.noMatches",
  replaceAllTooltip: "repoSearchDialog.replaceAllTooltip",
  repoSearchHint: "repoSearchDialog.repoSearchHint",
  replaceAllConfirmSuffix: "repoSearchDialog.replaceAllConfirmSuffix",
  replaceAllConfirmTemplate: "repoSearchDialog.replaceAllConfirmTemplate",
  replaceSummaryTemplate: "repoSearchDialog.replaceSummaryTemplate",
  filesHadErrorsTemplate: "repoSearchDialog.filesHadErrorsTemplate",
  foundMatchesTemplate: "repoSearchDialog.foundMatchesTemplate",
  fileMatchesChipTemplate: "repoSearchDialog.fileMatchesChipTemplate",
  lineLabelTemplate: "repoSearchDialog.lineLabelTemplate",
  extraMatchesTemplate: "repoSearchDialog.extraMatchesTemplate",
} as const;

export const REPO_SEARCH_TEXT = {
  title: enGbRepoSearchDialog.title,
  findLabel: enGbRepoSearchDialog.findLabel,
  findPlaceholder: enGbRepoSearchDialog.findPlaceholder,
  replaceLabel: enGbRepoSearchDialog.replaceLabel,
  replacePlaceholder: enGbRepoSearchDialog.replacePlaceholder,
  caseSensitive: enGbRepoSearchDialog.caseSensitive,
  useRegex: enGbRepoSearchDialog.useRegex,
  searching: enGbRepoSearchDialog.searching,
  searchButton: enGbRepoSearchDialog.searchButton,
  replaceAllButton: enGbRepoSearchDialog.replaceAllButton,
  replaceInFile: enGbRepoSearchDialog.replaceInFile,
  close: enGbRepoSearchDialog.close,
  searchFailed: enGbRepoSearchDialog.searchFailed,
  replaceFailed: enGbRepoSearchDialog.replaceFailed,
  emptyQueryError: enGbRepoSearchDialog.emptyQueryError,
  replaceMissingError: enGbRepoSearchDialog.replaceMissingError,
  noMatches: enGbRepoSearchDialog.noMatches,
  replaceAllTooltip: enGbRepoSearchDialog.replaceAllTooltip,
  repoSearchHint: enGbRepoSearchDialog.repoSearchHint,
  replaceAllConfirmSuffix: enGbRepoSearchDialog.replaceAllConfirmSuffix,
} as const;
