import { getDefaultTranslation } from "../../i18n/defaultTranslations";

export const REPO_SEARCH_KEYS = {
  title: "repoSearchDialog.title",
  findLabel: "repoSearchDialog.findLabel",
  findPlaceholder: "repoSearchDialog.findPlaceholder",
  replaceLabel: "repoSearchDialog.replaceLabel",
  replacePlaceholder: "repoSearchDialog.replacePlaceholder",
  caseSensitive: "repoSearchDialog.caseSensitive",
  useRegex: "repoSearchDialog.useRegex",
  searching: "repoSearchDialog.searching",
  searchButton: "repoSearchDialog.searchButton",
  replaceAllButton: "repoSearchDialog.replaceAllButton",
  replaceInFile: "repoSearchDialog.replaceInFile",
  close: "repoSearchDialog.close",
  searchFailed: "repoSearchDialog.searchFailed",
  replaceFailed: "repoSearchDialog.replaceFailed",
  emptyQueryError: "repoSearchDialog.emptyQueryError",
  replaceMissingError: "repoSearchDialog.replaceMissingError",
  noMatches: "repoSearchDialog.noMatches",
  replaceAllTooltip: "repoSearchDialog.replaceAllTooltip",
  repoSearchHint: "repoSearchDialog.repoSearchHint",
  replaceAllConfirmSuffix: "repoSearchDialog.replaceAllConfirmSuffix",
  replaceAllConfirmTemplate: "repoSearchDialog.replaceAllConfirmTemplate",
  replaceSummaryTemplate: "repoSearchDialog.replaceSummaryTemplate",
  filesHadErrorsTemplate: "repoSearchDialog.filesHadErrorsTemplate",
  foundMatchesTemplate: "repoSearchDialog.foundMatchesTemplate",
  fileMatchesChipTemplate: "repoSearchDialog.fileMatchesChipTemplate",
  lineLabelTemplate: "repoSearchDialog.lineLabelTemplate",
  extraMatchesTemplate: "repoSearchDialog.extraMatchesTemplate",
} as const;

const defaultText = (key: string): string => getDefaultTranslation(key);

export const REPO_SEARCH_TEXT = {
  title: defaultText(REPO_SEARCH_KEYS.title),
  findLabel: defaultText(REPO_SEARCH_KEYS.findLabel),
  findPlaceholder: defaultText(REPO_SEARCH_KEYS.findPlaceholder),
  replaceLabel: defaultText(REPO_SEARCH_KEYS.replaceLabel),
  replacePlaceholder: defaultText(REPO_SEARCH_KEYS.replacePlaceholder),
  caseSensitive: defaultText(REPO_SEARCH_KEYS.caseSensitive),
  useRegex: defaultText(REPO_SEARCH_KEYS.useRegex),
  searching: defaultText(REPO_SEARCH_KEYS.searching),
  searchButton: defaultText(REPO_SEARCH_KEYS.searchButton),
  replaceAllButton: defaultText(REPO_SEARCH_KEYS.replaceAllButton),
  replaceInFile: defaultText(REPO_SEARCH_KEYS.replaceInFile),
  close: defaultText(REPO_SEARCH_KEYS.close),
  searchFailed: defaultText(REPO_SEARCH_KEYS.searchFailed),
  replaceFailed: defaultText(REPO_SEARCH_KEYS.replaceFailed),
  emptyQueryError: defaultText(REPO_SEARCH_KEYS.emptyQueryError),
  replaceMissingError: defaultText(REPO_SEARCH_KEYS.replaceMissingError),
  noMatches: defaultText(REPO_SEARCH_KEYS.noMatches),
  replaceAllTooltip: defaultText(REPO_SEARCH_KEYS.replaceAllTooltip),
  repoSearchHint: defaultText(REPO_SEARCH_KEYS.repoSearchHint),
  replaceAllConfirmSuffix: defaultText(
    REPO_SEARCH_KEYS.replaceAllConfirmSuffix,
  ),
} as const;
