import { getDefaultTranslation } from "../../i18n/defaultTranslations";

export const REPO_SETUP_KEYS = {
  title: "repoSetupDialog.title",
  description: "repoSetupDialog.description",
  repoTypeLabel: "repoSetupDialog.repoTypeLabel",
  gitLabel: "repoSetupDialog.gitLabel",
  s3Label: "repoSetupDialog.s3Label",
  localLabel: "repoSetupDialog.localLabel",
  cancel: "repoSetupDialog.cancel",
  connect: "repoSetupDialog.connect",
  connecting: "repoSetupDialog.connecting",
  gitRequired: "repoSetupDialog.gitRequired",
  s3Required: "repoSetupDialog.s3Required",
  localRequired: "repoSetupDialog.localRequired",
  connectFailed: "repoSetupDialog.connectFailed",
  gitRemoteUrlLabel: "repoSetupDialog.gitRemoteUrlLabel",
  gitRemoteUrlPlaceholder: "repoSetupDialog.gitRemoteUrlPlaceholder",
  gitBranchLabel: "repoSetupDialog.gitBranchLabel",
  gitBranchPlaceholder: "repoSetupDialog.gitBranchPlaceholder",
  gitPatLabel: "repoSetupDialog.gitPatLabel",
  gitPatPlaceholder: "repoSetupDialog.gitPatPlaceholder",
  patHelper: "repoSetupDialog.patHelper",
  patGuideTitle: "repoSetupDialog.patGuide.title",
  s3BucketLabel: "repoSetupDialog.s3BucketLabel",
  s3BucketPlaceholder: "repoSetupDialog.s3BucketPlaceholder",
  s3RegionLabel: "repoSetupDialog.s3RegionLabel",
  s3RegionPlaceholder: "repoSetupDialog.s3RegionPlaceholder",
  s3PrefixLabel: "repoSetupDialog.s3PrefixLabel",
  s3PrefixPlaceholder: "repoSetupDialog.s3PrefixPlaceholder",
  s3AccessKeyIdLabel: "repoSetupDialog.s3AccessKeyIdLabel",
  s3SecretAccessKeyLabel: "repoSetupDialog.s3SecretAccessKeyLabel",
  s3SessionTokenLabel: "repoSetupDialog.s3SessionTokenLabel",
  s3SecretHelper: "repoSetupDialog.s3SecretHelper",
  s3Info: "repoSetupDialog.s3Info",
  localRepoNameLabel: "repoSetupDialog.localRepoNameLabel",
  localRepoNamePlaceholder: "repoSetupDialog.localRepoNamePlaceholder",
  localRepoNameHelper: "repoSetupDialog.localRepoNameHelper",
  localInfo: "repoSetupDialog.localInfo",
  patGuideLine1: "repoSetupDialog.patGuide.line1",
  patGuideLine2: "repoSetupDialog.patGuide.line2",
  patGuideLine3: "repoSetupDialog.patGuide.line3",
  patGuideLine4: "repoSetupDialog.patGuide.line4",
  patGuideLine5: "repoSetupDialog.patGuide.line5",
  patGuideLine6: "repoSetupDialog.patGuide.line6",
  patGuideLine7: "repoSetupDialog.patGuide.line7",
  patGuideLine8: "repoSetupDialog.patGuide.line8",
  patGuideLine9: "repoSetupDialog.patGuide.line9",
  patGuideLine10: "repoSetupDialog.patGuide.line10",
  patGuideLine11: "repoSetupDialog.patGuide.line11",
} as const;

const defaultText = (key: string): string => getDefaultTranslation(key);

export const REPO_SETUP_TEXT = {
  title: defaultText(REPO_SETUP_KEYS.title),
  description: defaultText(REPO_SETUP_KEYS.description),
  repoTypeLabel: defaultText(REPO_SETUP_KEYS.repoTypeLabel),
  gitLabel: defaultText(REPO_SETUP_KEYS.gitLabel),
  s3Label: defaultText(REPO_SETUP_KEYS.s3Label),
  localLabel: defaultText(REPO_SETUP_KEYS.localLabel),
  cancel: defaultText(REPO_SETUP_KEYS.cancel),
  connect: defaultText(REPO_SETUP_KEYS.connect),
  connecting: defaultText(REPO_SETUP_KEYS.connecting),
  gitRequired: defaultText(REPO_SETUP_KEYS.gitRequired),
  s3Required: defaultText(REPO_SETUP_KEYS.s3Required),
  localRequired: defaultText(REPO_SETUP_KEYS.localRequired),
  connectFailed: defaultText(REPO_SETUP_KEYS.connectFailed),
  patHelper: defaultText(REPO_SETUP_KEYS.patHelper),
  s3SecretHelper: defaultText(REPO_SETUP_KEYS.s3SecretHelper),
  s3Info: defaultText(REPO_SETUP_KEYS.s3Info),
  localInfo: defaultText(REPO_SETUP_KEYS.localInfo),
} as const;
