import enGbRepoSetupDialog from "../../i18n/en-GB/repoSetupDialog.json";

export const REPO_SETUP_KEYS = {
  title: "repoSetupDialog.title",
  description: "repoSetupDialog.description",
  repoTypeLabel: "repoSetupDialog.repoTypeLabel",
  gitLabel: "repoSetupDialog.gitLabel",
  s3Label: "repoSetupDialog.s3Label",
  localLabel: "repoSetupDialog.localLabel",
  cancel: "repoSetupDialog.cancel",
  connect: "repoSetupDialog.connect",
  connecting: "repoSetupDialog.connecting",
  gitRequired: "repoSetupDialog.gitRequired",
  s3Required: "repoSetupDialog.s3Required",
  localRequired: "repoSetupDialog.localRequired",
  connectFailed: "repoSetupDialog.connectFailed",
  gitRemoteUrlLabel: "repoSetupDialog.gitRemoteUrlLabel",
  gitRemoteUrlPlaceholder: "repoSetupDialog.gitRemoteUrlPlaceholder",
  gitBranchLabel: "repoSetupDialog.gitBranchLabel",
  gitBranchPlaceholder: "repoSetupDialog.gitBranchPlaceholder",
  gitPatLabel: "repoSetupDialog.gitPatLabel",
  gitPatPlaceholder: "repoSetupDialog.gitPatPlaceholder",
  patHelper: "repoSetupDialog.patHelper",
  patGuideTitle: "repoSetupDialog.patGuide.title",
  s3BucketLabel: "repoSetupDialog.s3BucketLabel",
  s3BucketPlaceholder: "repoSetupDialog.s3BucketPlaceholder",
  s3RegionLabel: "repoSetupDialog.s3RegionLabel",
  s3RegionPlaceholder: "repoSetupDialog.s3RegionPlaceholder",
  s3PrefixLabel: "repoSetupDialog.s3PrefixLabel",
  s3PrefixPlaceholder: "repoSetupDialog.s3PrefixPlaceholder",
  s3AccessKeyIdLabel: "repoSetupDialog.s3AccessKeyIdLabel",
  s3SecretAccessKeyLabel: "repoSetupDialog.s3SecretAccessKeyLabel",
  s3SessionTokenLabel: "repoSetupDialog.s3SessionTokenLabel",
  s3SecretHelper: "repoSetupDialog.s3SecretHelper",
  s3Info: "repoSetupDialog.s3Info",
  localRepoNameLabel: "repoSetupDialog.localRepoNameLabel",
  localRepoNamePlaceholder: "repoSetupDialog.localRepoNamePlaceholder",
  localRepoNameHelper: "repoSetupDialog.localRepoNameHelper",
  localInfo: "repoSetupDialog.localInfo",
  patGuideLine1: "repoSetupDialog.patGuide.line1",
  patGuideLine2: "repoSetupDialog.patGuide.line2",
  patGuideLine3: "repoSetupDialog.patGuide.line3",
  patGuideLine4: "repoSetupDialog.patGuide.line4",
  patGuideLine5: "repoSetupDialog.patGuide.line5",
  patGuideLine6: "repoSetupDialog.patGuide.line6",
  patGuideLine7: "repoSetupDialog.patGuide.line7",
  patGuideLine8: "repoSetupDialog.patGuide.line8",
  patGuideLine9: "repoSetupDialog.patGuide.line9",
  patGuideLine10: "repoSetupDialog.patGuide.line10",
  patGuideLine11: "repoSetupDialog.patGuide.line11",
} as const;

export const REPO_SETUP_TEXT = {
  title: enGbRepoSetupDialog.title,
  description: enGbRepoSetupDialog.description,
  repoTypeLabel: enGbRepoSetupDialog.repoTypeLabel,
  gitLabel: enGbRepoSetupDialog.gitLabel,
  s3Label: enGbRepoSetupDialog.s3Label,
  localLabel: enGbRepoSetupDialog.localLabel,
  cancel: enGbRepoSetupDialog.cancel,
  connect: enGbRepoSetupDialog.connect,
  connecting: enGbRepoSetupDialog.connecting,
  gitRequired: enGbRepoSetupDialog.gitRequired,
  s3Required: enGbRepoSetupDialog.s3Required,
  localRequired: enGbRepoSetupDialog.localRequired,
  connectFailed: enGbRepoSetupDialog.connectFailed,
  patHelper: enGbRepoSetupDialog.patHelper,
  s3SecretHelper: enGbRepoSetupDialog.s3SecretHelper,
  s3Info: enGbRepoSetupDialog.s3Info,
  localInfo: enGbRepoSetupDialog.localInfo,
} as const;
