export const FILE_TREE_TEXT = {
  newFile: 'New File',
  newFolder: 'New Folder',
  importFile: 'Import File',
  rename: 'Rename',
  delete: 'Delete',
  duplicate: 'Duplicate',
  moveToFolder: 'Move to folder',
  createFileTitle: 'Create New File',
  createFolderTitle: 'Create New Folder',
  renameFileTitle: 'Rename File',
  renameFolderTitle: 'Rename Folder',
  fileNameLabel: 'File Name',
  folderNameLabel: 'Folder Name',
  newNameLabel: 'New Name',
  filePlaceholder: 'my-note (extension optional)',
  folderPlaceholder: 'my-folder',
  fileExtensionHint: 'Extension will be auto-added as .md if not specified',
  createLocationRoot: 'Will be created in root directory',
  createLocationPrefix: 'Will be created in: ',
  cancel: 'Cancel',
  create: 'Create',
  creating: 'Creating...',
  renameAction: 'Rename',
  renaming: 'Renaming...',
  favoritesTitle: 'Favorites',
  addToFavorites: 'Add selection to favorites',
  removeFromFavorites: 'Remove selection from favorites',
  favoritesContextMenuItem: 'Remove from favorites',
} as const;

export const INVALID_NAME_CHARS = /[<>:"/\\|?*]/;
export const FAVORITES_STORAGE_KEY = 'notegit-tree-favorites';
