export const FILE_TREE_TEXT = {
  newFile: 'New File',
  newFolder: 'New Folder',
  importFile: 'Import File',
  collapseAll: 'Collapse All',
  rename: 'Rename',
  delete: 'Delete',
  duplicate: 'Duplicate',
  moveToFolder: 'Move to folder',
  createFileTitle: 'Create New File',
  createFolderTitle: 'Create New Folder',
  renameFileTitle: 'Rename File',
  renameFolderTitle: 'Rename Folder',
  fileNameLabel: 'File Name',
  folderNameLabel: 'Folder Name',
  newNameLabel: 'New Name',
  filePlaceholder: 'my-note (extension optional)',
  folderPlaceholder: 'my-folder',
  fileExtensionHint: 'Extension will be auto-added as .md if not specified',
  createLocationRoot: 'Will be created in root directory',
  createLocationPrefix: 'Will be created in: ',
  cancel: 'Cancel',
  create: 'Create',
  creating: 'Creating...',
  renameAction: 'Rename',
  renaming: 'Renaming...',
  favoritesTitle: 'Favorites',
  addToFavorites: 'Add selection to favorites',
  removeFromFavorites: 'Remove selection from favorites',
  favoritesContextMenuItem: 'Remove from favorites',
} as const;

export const FILE_TREE_MESSAGES = {
  invalidFileName: 'File name contains invalid characters: < > : " / \\ | ? *',
  invalidFolderName: 'Folder name contains invalid characters: < > : " / \\ | ? *',
  invalidRenameName: 'Name contains invalid characters: < > : " / \\ | ? *',
  emptyName: 'Name cannot be empty',
  fileAlreadyExists: (name: string) => `File "${name}" already exists`,
  folderAlreadyExists: (name: string) => `Folder "${name}" already exists`,
  permissionDeniedCreateFile: 'Permission denied to create file',
  permissionDeniedCreateFolder: 'Permission denied to create folder',
  permissionDenied: 'Permission denied',
  failedCreateFile: 'Failed to create file',
  failedCreateFolder: 'Failed to create folder',
  failedRename: 'Failed to rename',
  dialogApiNotAvailable: 'Dialog API not available. Please restart the app.',
  importDialogTitle: 'Select file to import',
  importedFileNameFallback: 'imported_file',
  unknownError: 'Unknown error',
  renameAlreadyExists: (itemType: 'file' | 'folder') =>
    `A ${itemType} with that name already exists`,
  deleteConfirmation: (itemType: 'folder' | 'file', name: string, isFolder: boolean) =>
    `Are you sure you want to delete ${itemType} "${name}"?${isFolder ? ' All contents will be deleted.' : ''}`,
  failedDeletePrefix: 'Failed to delete',
  failedImportPrefix: 'Failed to import file',
  failedMovePrefix: 'Failed to move',
} as const;

export const INVALID_NAME_CHARS = /[<>:"/\\|?*]/;
export const FAVORITES_STORAGE_KEY = 'notegit-tree-favorites';
